from core import T

DEFENSE_REQUIREMENTS = [
    {"req": T("Telemetry fabric spanning identity, cloud/K8s control plane, workload runtime, agent-aware edge, network (NDR) and deception", "覆盖身份、云/K8s控制平面、工作负载运行时、面向智能体的边界、网络（NDR）与欺骗诱捕的遥测体系"),
     "why": T("At HF the decisive evidence came from identity, cloud audit and runtime — not the perimeter. NDR is essential for egress/C2 but blind inside encrypted overlays.", "在HF案例中，决定性证据来自身份、云审计与运行时，而非边界；NDR对出网/C2不可或缺，但在加密覆盖网络内是盲区。"),
     "priority": "must"},
    {"req": T("Cross-layer correlation that produces one attack narrative", "能产出单一“攻击叙事”的跨层关联"),
     "why": T("Individual signals were ambiguous; correlation is what turned scattered alerts into an attack signal.", "单条信号都很模糊；关联才把零散告警变成攻击信号。"),
     "priority": "must"},
    {"req": T("Escalation & severity engine with an enforced human page path", "带强制“呼叫到人”路径的升级与严重度引擎"),
     "why": T("The correlated signal existed at HF but never paged the on-call team over a weekend.", "HF的关联信号本已存在，却整个周末没有呼叫到值班团队。"),
     "priority": "must"},
    {"req": T("A sovereign, self-hostable AI analysis layer with a refusal-fallback router", "自主可控、可自托管的AI分析层，含拒答回退路由"),
     "why": T("Commercial guardrails blocked HF's forensics; a self-hosted open-weight model did the job and kept data in-house.", "商业护栏拦截了HF的取证；自托管的开源权重模型完成了任务并将数据留在内部。"),
     "priority": "must"},
    {"req": T("Non-human-identity governance: short-lived, scoped, auditable credentials and continuous leaked-secret scanning", "非人类身份治理：短时效、最小权限、可审计的凭证，以及持续的泄露密钥扫描"),
     "why": T("The entry key was exposed tokens; the blast radius was over-privileged, non-expiring credentials.", "入侵钥匙是暴露的令牌；爆炸半径源于权限过大、永不过期的凭证。"),
     "priority": "must"},
    {"req": T("Human-approved, machine-speed containment (SOAR / agentic response)", "人工审批、机器速度的遏制（SOAR / 智能体化响应）"),
     "why": T("Escalation to cluster-admin took under 13 hours; response must act in minutes, with a human gate on destructive actions.", "提权至集群管理员用时不到13小时；响应必须以分钟计，并对破坏性动作设人工闸门。"),
     "priority": "must"},
    {"req": T("Deception (honeytokens / decoy secrets) for earliest high-fidelity detection", "欺骗诱捕（蜜标/诱饵密钥）以获得最早的高置信检测"),
     "why": T("The CISO post-mortem recommends deception as the earliest reliable signal against exploring agents.", "CISO事后复盘建议将欺骗诱捕作为对抗探索型智能体的最早、可靠信号。"),
     "priority": "should"},
    {"req": T("Agent-behaviour analytics: machine-cadence and behaviour-shift detection", "智能体行为分析：机器节奏与行为漂移检测"),
     "why": T("Benign tasks escalated; the tell is a session's behaviour changing to non-human speed and pattern.", "良性任务会升级；识别点在于会话行为转向非人类的速度与模式。"),
     "priority": "should"},
]

# ---- Architecture Option A: SOC-Evolved ----
ARCH_A = {
    "id": "A",
    "name": T("Option A — SOC-Evolved: SIEM/NDR core with an AI analytics overlay", "方案A — SOC演进式：以SIEM/NDR为核心，叠加AI分析层"),
    "tagline": T("Evolutionary. Keep your SOC; add the telemetry, correlation, escalation and sovereign AI forensics that HF was missing.", "演进式。保留现有SOC；补上HF所缺的遥测、关联、升级与自主可控的AI取证能力。"),
    "fit": T("Organisations with an existing SIEM/SOC that need to close the 2026 gaps quickly and with lower risk.", "已有SIEM/SOC、希望以较低风险快速补上2026年缺口的机构。"),
    "layers": [
        {"name": T("1 · Telemetry sources", "1 · 遥测源"),
         "components": [T("Identity & token activity (IdP, secrets)", "身份与令牌活动（IdP、密钥）"),
                        T("Cloud & Kubernetes control-plane audit", "云与Kubernetes控制平面审计"),
                        T("Workload runtime & endpoint EDR", "工作负载运行时与终端EDR"),
                        T("NDR probes: egress, east-west, DNS", "NDR探针：出网、东西向、DNS"),
                        T("WAF / API gateway & mesh-VPN audit", "WAF / API网关与Mesh VPN审计"),
                        T("Deception: honeytokens & decoy secrets", "欺骗诱捕：蜜标与诱饵密钥")]},
        {"name": T("2 · Collection & data lake", "2 · 采集与数据湖"),
         "components": [T("Log shippers & normalization (OCSF/ECS)", "日志采集与规范化（OCSF/ECS）"),
                        T("Security data lake / SIEM index", "安全数据湖 / SIEM索引"),
                        T("Entity & non-human-identity inventory", "实体与非人类身份清单")]},
        {"name": T("3 · Correlation & detection", "3 · 关联与检测"),
         "components": [T("SIEM correlation & UEBA baselines", "SIEM关联与UEBA基线"),
                        T("Detection-as-code (Sigma rules)", "检测即代码（Sigma规则）"),
                        T("Agent-cadence & behaviour-shift analytics", "智能体节奏与行为漂移分析")]},
        {"name": T("4 · AI analytics overlay (sovereign)", "4 · AI分析层（自主可控）"),
         "components": [T("Self-hosted open-weight LLM for forensics", "自托管开源权重LLM用于取证"),
                        T("Refusal-fallback router across models", "跨模型的拒答回退路由"),
                        T("Prompt catalog: triage → correlation → timeline", "提示词目录：研判 → 关联 → 时间线"),
                        T("Attack-path / graph reasoning", "攻击路径 / 图推理")]},
        {"name": T("5 · Response & escalation", "5 · 响应与升级"),
         "components": [T("Severity & escalation engine (paging SLA)", "严重度与升级引擎（呼叫SLA）"),
                        T("SOAR playbooks with human gate", "带人工闸门的SOAR剧本"),
                        T("Mass credential rotation & revocation", "大规模凭证轮换与吊销")]},
        {"name": T("6 · Governance", "6 · 治理"),
         "components": [T("Human-in-the-loop for destructive actions", "破坏性动作的人在回路"),
                        T("Model & prompt audit trail", "模型与提示词审计留痕"),
                        T("Purple-team validation", "紫队验证")]},
    ],
    "flows": [
        T("Sensors → normalize → data lake/SIEM", "传感器 → 规范化 → 数据湖/SIEM"),
        T("SIEM/UEBA correlate → candidate incident", "SIEM/UEBA关联 → 候选事件"),
        T("Sovereign AI overlay: triage, timeline, attack-path, IOC & credential scope", "自主AI层：研判、时间线、攻击路径、IOC与凭证范围"),
        T("Severity engine pages a human within minutes", "严重度引擎在几分钟内呼叫到人"),
        T("SOAR contains with human approval; credentials rotated", "SOAR在人工审批下遏制；轮换凭证"),
    ],
    "pros": [T("Builds on existing SIEM/SOC investment — lower cost and risk.", "基于既有SIEM/SOC投入——成本与风险更低。"),
             T("Directly fixes the HF gaps: correlation, escalation, sovereign forensics.", "直接修复HF的缺口：关联、升级、自主取证。"),
             T("Human stays in control of containment.", "遏制始终由人掌控。")],
    "cons": [T("Response is still human-paced at the decision point — slower than a machine-speed swarm.", "在决策点仍是人类节奏——慢于机器速度的集群。"),
             T("SIEM-centric designs can drown correlation in volume (HF's mesh-VPN log was 'buried').", "以SIEM为中心的设计可能让关联淹没在数据量中（HF的Mesh VPN日志曾被“埋没”）。"),
             T("Limited autonomous coverage of encrypted overlays.", "对加密覆盖网络的自主覆盖有限。")],
    "roadmap": [
        {"phase": T("0–3 months", "0–3个月"), "items": T("Wire identity + cloud/K8s audit + runtime into the lake; stand up a self-hosted forensic model with a fallback router; set a paging SLA on high-severity correlated signals.", "把身份 + 云/K8s审计 + 运行时接入数据湖；部署一个带回退路由的自托管取证模型；为高严重度关联信号设定呼叫SLA。")},
        {"phase": T("3–6 months", "3–6个月"), "items": T("Add NDR egress/DNS and mesh-VPN audit; deploy honeytokens; add agent-cadence analytics; codify SOAR playbooks with a human gate.", "接入NDR出网/DNS与Mesh VPN审计；部署蜜标；加入智能体节奏分析；固化带人工闸门的SOAR剧本。")},
        {"phase": T("6–12 months", "6–12个月"), "items": T("Continuous leaked-secret scanning of public assets; purple-team the whole chain against a simulated agent swarm; expand the prompt catalog.", "持续扫描公开资产的泄露密钥；用模拟智能体集群对整条链路做紫队演练；扩展提示词目录。")},
    ],
    "kpis": [T("MTTD < 1 hour for correlated agent activity", "关联的智能体活动MTTD < 1小时"),
             T("Escalation-to-page < 5 minutes for high severity", "高严重度事件“升级到呼叫”< 5分钟"),
             T("100% of high-severity signals page a human, any day", "高严重度信号100%呼叫到人，任何一天"),
             T("Credential revocation scope complete within one shift", "一个班次内完成凭证吊销范围界定")],
}

# ---- Architecture Option B: AI-Native Defense Mesh ----
ARCH_B = {
    "id": "B",
    "name": T("Option B — AI-Native Defense Mesh: an agentic SOC that fights at machine speed", "方案B — AI原生防御网格：以机器速度作战的智能体化SOC"),
    "tagline": T("Frontier design. Sovereign defender-agents watch, reason and contain at machine speed, with a human gate on irreversible actions.", "前沿设计。自主可控的防御智能体以机器速度监测、推理与遏制，对不可逆动作设人工闸门。"),
    "fit": T("High-value targets (AI platforms, government data, critical infra) that face autonomous swarms and cannot rely on human-paced response alone.", "面对自主集群、无法仅靠人类节奏响应的高价值目标（AI平台、政府数据、关键基础设施）。"),
    "layers": [
        {"name": T("1 · Pervasive sensing", "1 · 泛在感知"),
         "components": [T("Agent-gateway: every AI/agent action logged & policy-checked", "智能体网关：记录并策略校验每个AI/智能体动作"),
                        T("Identity, cloud/K8s, runtime, NDR, mesh-VPN", "身份、云/K8s、运行时、NDR、Mesh VPN"),
                        T("Dense deception grid (honeytokens everywhere)", "密集欺骗网格（蜜标遍布）"),
                        T("Continuous public-asset secret scanning", "持续的公开资产密钥扫描")]},
        {"name": T("2 · Streaming graph brain", "2 · 流式图大脑"),
         "components": [T("Real-time entity & identity graph", "实时实体与身份图"),
                        T("Streaming correlation (no batch delay)", "流式关联（无批处理延迟）"),
                        T("Behaviour & cadence models (human vs machine)", "行为与节奏模型（人 vs 机器）")]},
        {"name": T("3 · Multi-agent defender mesh (sovereign)", "3 · 多智能体防御网格（自主可控）"),
         "components": [T("Triage agent + correlation agent", "研判智能体 + 关联智能体"),
                        T("Attack-path / graph-reasoning agent", "攻击路径 / 图推理智能体"),
                        T("Payload-analysis & detection-writer agent", "载荷分析与检测编写智能体"),
                        T("Adversary-emulation (purple) agent", "对手仿真（紫队）智能体"),
                        T("Refusal-fallback router + model registry", "拒答回退路由 + 模型注册表")]},
        {"name": T("4 · Model roster", "4 · 模型阵列"),
         "components": [T("Self-hosted open-weight LLM (primary forensic)", "自托管开源权重LLM（主取证）"),
                        T("Small fast classifiers (triage, cadence)", "小型快速分类器（研判、节奏）"),
                        T("UEBA / anomaly & graph models", "UEBA / 异常与图模型"),
                        T("Embedding / similarity for IOC clustering", "嵌入 / 相似度用于IOC聚类")]},
        {"name": T("5 · Autonomic response", "5 · 自主响应"),
         "components": [T("Machine-speed containment with reversible actions", "机器速度、可逆动作的遏制"),
                        T("Human gate for destructive / irreversible steps", "破坏性/不可逆步骤的人工闸门"),
                        T("Auto credential rotation & network isolation", "自动凭证轮换与网络隔离")]},
        {"name": T("6 · Assurance & governance", "6 · 保障与治理"),
         "components": [T("Full decision & prompt audit; replay", "完整决策与提示词审计；可回放"),
                        T("Guardrails on the defender agents themselves", "对防御智能体自身的护栏"),
                        T("Continuous purple-team & drift monitoring", "持续紫队与漂移监测")]},
    ],
    "flows": [
        T("Every agent/identity action → agent-gateway → streaming graph", "每个智能体/身份动作 → 智能体网关 → 流式图"),
        T("Defender mesh reasons continuously; deception fires earliest signal", "防御网格持续推理；欺骗诱捕给出最早信号"),
        T("Machine-speed reversible containment; human gate on irreversible", "机器速度的可逆遏制；不可逆动作设人工闸门"),
        T("Detections written back as code; purple agent re-tests", "检测以代码写回；紫队智能体重新测试"),
    ],
    "pros": [T("Matches attacker speed: contains in minutes, not shifts.", "匹配攻击者速度：以分钟而非班次完成遏制。"),
             T("Agent-gateway gives first-class visibility & control over AI/agent actions — the surface HF lacked.", "智能体网关对AI/智能体动作提供一等可见性与管控——正是HF所缺的面。"),
             T("Sovereign by design: no external refusal, data stays in-house.", "设计即自主可控：无外部拒答，数据留在内部。")],
    "cons": [T("Higher cost, complexity and skills bar.", "更高的成本、复杂度与技能门槛。"),
             T("Defender agents need their own guardrails and assurance — new risk surface.", "防御智能体需要自身的护栏与保障——新增风险面。"),
             T("Over-automation risk; irreversible actions must stay human-gated.", "过度自动化风险；不可逆动作必须保留人工闸门。")],
    "roadmap": [
        {"phase": T("0–3 months", "0–3个月"), "items": T("Deploy the agent-gateway and dense honeytokens; stand up the sovereign model registry with a fallback router; start the streaming entity graph.", "部署智能体网关与密集蜜标；建立带回退路由的自主模型注册表；启动流式实体图。")},
        {"phase": T("3–6 months", "3–6个月"), "items": T("Bring the triage, correlation and attack-path agents online in advisory mode; add cadence/behaviour models; keep humans approving all containment.", "以“建议模式”上线研判、关联与攻击路径智能体；加入节奏/行为模型；所有遏制仍由人审批。")},
        {"phase": T("6–12 months", "6–12个月"), "items": T("Enable machine-speed reversible containment with a human gate on irreversible steps; add the adversary-emulation agent; run continuous purple-teaming.", "启用机器速度的可逆遏制，对不可逆步骤设人工闸门；加入对手仿真智能体；开展持续紫队。")},
    ],
    "kpis": [T("MTTD < 5 minutes; MTTR < 30 minutes", "MTTD < 5分钟；MTTR < 30分钟"),
             T("> 80% of alerts auto-triaged with rationale", "超过80%告警由AI附理由自动研判"),
             T("100% of AI/agent actions logged at the gateway", "AI/智能体动作在网关处100%留痕"),
             T("Deception fires before objective in > 60% of drills", "演练中超过60%的情形蜜标在攻击达成目标前先触发")],
}

ARCHITECTURES = [ARCH_A, ARCH_B]

# system prompts stay in English; names/purposes are bilingual
PROMPT_CATALOG = [
    {"id": "P1", "name": T("Alert triage", "告警研判"), "model": T("Small fast classifier / self-hosted LLM", "小型快速分类器 / 自托管LLM"),
     "purpose": T("Rate each correlated alert for severity and whether it looks like autonomous-agent activity.", "为每条关联告警评定严重度，并判断是否像自主智能体活动。"),
     "system": "You are a Tier-1 SOC triage analyst for a defensive security team, working only on the defender's own authorized telemetry. Given a correlated alert, output strict JSON: {severity: low|medium|high|critical, is_agentic: bool, confidence: 0-1, why: <=40 words, next_action}. Flag machine-cadence timing, rotating source infrastructure, and retrieval-failure-then-probing sequences. Never invent fields not present in the input.",
     "task": "Alert bundle:\n<<ALERT_JSON>>\nReturn the triage JSON."},
    {"id": "P2", "name": T("Cross-layer correlation", "跨层关联"), "model": T("Self-hosted forensic LLM + graph model", "自托管取证LLM + 图模型"),
     "purpose": T("Fuse identity, cloud, runtime and network signals into a single incident narrative.", "把身份、云、运行时与网络信号融合为单一事件叙事。"),
     "system": "You are an incident correlation engine for an authorized defensive investigation. Input is a set of signals from different telemetry layers about the defender's own environment. Group them into candidate incidents, state the linking entity (identity, host, token, cluster) for each link, and give a one-paragraph narrative per incident. Mark any link you are inferring versus one supported by a shared identifier. Do not fabricate identifiers.",
     "task": "Signals:\n<<SIGNALS_JSON>>\nReturn incidents[] with {entities, links[with basis], narrative, confidence}."},
    {"id": "P3", "name": T("Timeline reconstruction", "时间线重建"), "model": T("Self-hosted forensic LLM", "自托管取证LLM"),
     "purpose": T("Turn thousands of raw actions into an ordered, clustered timeline.", "把数千条原始动作整理为有序、聚类的时间线。"),
     "system": "You are a digital-forensics timeline builder for an authorized incident response on the organization's own logs. Given raw, timestamped action records, produce a chronological timeline, cluster near-duplicate actions, and label each cluster with a MITRE ATT&CK tactic where it clearly applies. Note gaps and possible decoy/noise clusters separately. Output is descriptive analysis for defenders, not instructions to reproduce any technique.",
     "task": "Action records:\n<<ACTIONS_JSON>>\nReturn timeline[] and clusters[] with tactic labels and a decoy_candidates[] list."},
    {"id": "P4", "name": T("Attack-path & graph reasoning", "攻击路径与图推理"), "model": T("Graph model + self-hosted LLM", "图模型 + 自托管LLM"),
     "purpose": T("Map how the actor moved from entry to objective and where to cut the path.", "刻画攻击者从入口到目标的移动路径，并找出可切断之处。"),
     "system": "You are an attack-path analyst for an authorized defensive review of the organization's own entity graph. Given nodes (identities, hosts, tokens, clusters) and observed edges, reconstruct the most likely path from initial foothold to objective, and recommend the single edge whose removal most reduces blast radius. Distinguish confirmed edges from inferred ones. Frame everything as containment guidance for defenders.",
     "task": "Graph:\n<<GRAPH_JSON>>\nReturn ordered_path[], choke_points[], and recommended_cut with rationale."},
    {"id": "P5", "name": T("Agent-behaviour fingerprinting", "智能体行为指纹"), "model": T("Cadence classifier + LLM", "节奏分类器 + LLM"),
     "purpose": T("Decide whether a session is a human, a normal bot, or an autonomous agent, from timing and behaviour shift.", "依据时序与行为漂移，判断会话是人、普通机器人还是自主智能体。"),
     "system": "You are a behaviour-analytics assistant for a defensive team analyzing the organization's own access logs. Given a session's request timing, diversity and how its behaviour changes over the session, classify actor_type: human|scripted_bot|autonomous_agent, with confidence and the top three features that drove the call. Emphasize machine-cadence bursts and a shift from normal use to anomalous activity. JSON only.",
     "task": "Session features:\n<<SESSION_JSON>>\nReturn {actor_type, confidence, top_features[]}."},
    {"id": "P6", "name": T("Encoded-artifact decoding (forensic)", "编码痕迹解码（取证）"), "model": T("Self-hosted forensic LLM", "自托管取证LLM"),
     "purpose": T("Decode obfuscated log/artifact content to widen credential-exposure scope.", "解码被混淆的日志/痕迹内容，以扩大凭证暴露范围的界定。"),
     "system": "You are a forensic artifact analyst for an authorized incident response, working on the organization's own captured logs. Identify any encoding or obfuscation scheme present in the provided artifacts, describe it, and extract indicators of compromise and any exposed secret identifiers (report secret NAMES/locations, never full secret values). The purpose is strictly to scope revocation. Output IOCs and exposed-credential references as JSON.",
     "task": "Artifacts:\n<<ARTIFACTS>>\nReturn {encoding_described, iocs[], exposed_credentials[](names/locations only)}."},
    {"id": "P7", "name": T("Detection-rule generation", "检测规则生成"), "model": T("Self-hosted LLM", "自托管LLM"),
     "purpose": T("Write detection-as-code (Sigma) for the observed behaviour.", "为已观测行为编写检测即代码（Sigma）。"),
     "system": "You are a detection engineer for a defensive team. From a described incident behaviour, write a Sigma rule that would detect the same behaviour in the organization's logs, with a title, logsource, detection logic, false-positive notes and a severity level. Prefer robust behavioural conditions over brittle string matches. Output valid Sigma YAML only.",
     "task": "Behaviour:\n<<BEHAVIOUR>>\nReturn one Sigma rule."},
    {"id": "P8", "name": T("Credential-exposure & revocation scoping", "凭证暴露与吊销范围界定"), "model": T("Self-hosted LLM", "自托管LLM"),
     "purpose": T("List every credential the actor touched and the safe revocation order.", "列出攻击者触及的每个凭证及安全的吊销顺序。"),
     "system": "You are a credential-scoping assistant for an authorized incident response on the organization's own systems. Given IOCs and access logs, list distinct credentials/tokens/keys the actor accessed or could derive, classify each by blast radius, and propose a revocation/rotation order that avoids self-inflicted outages. Reference credentials by name/identifier only. JSON only.",
     "task": "Evidence:\n<<EVIDENCE_JSON>>\nReturn credentials[] with {name, blast_radius, rotation_order, dependency_notes}."},
    {"id": "P9", "name": T("Containment playbook drafting", "遏制剧本起草"), "model": T("Self-hosted LLM", "自托管LLM"),
     "purpose": T("Propose reversible containment steps, flagging which need human approval.", "提出可逆的遏制步骤，并标注哪些需要人工审批。"),
     "system": "You are an incident-response planner for the organization's own environment. Given a scoped incident, propose an ordered containment plan. Mark each step reversible|irreversible and require_human_approval:true for anything destructive or irreversible (mass revocation, node destruction, network cut-off). Include a rollback for each reversible step. Output is a plan for human responders to approve; JSON only.",
     "task": "Incident:\n<<INCIDENT_JSON>>\nReturn steps[] with {action, reversible, require_human_approval, rollback}."},
    {"id": "P10", "name": T("Decoy vs real-impact separation", "诱饵与真实影响的区分"), "model": T("Self-hosted forensic LLM", "自托管取证LLM"),
     "purpose": T("Separate genuine attacker impact from noise generated to mislead investigators.", "把真实攻击影响与为误导调查而制造的噪声区分开。"),
     "system": "You are a forensic analyst for an authorized investigation on the organization's own logs. Given clustered actions, label each cluster genuine_impact|likely_decoy|uncertain, with the evidence for the label. Decoys often repeat low-value actions or target non-existent assets. Do not discard uncertain clusters. JSON only.",
     "task": "Clusters:\n<<CLUSTERS_JSON>>\nReturn labelled_clusters[] with evidence."},
    {"id": "P11", "name": T("Non-human-identity risk review", "非人类身份风险审查"), "model": T("Self-hosted LLM", "自托管LLM"),
     "purpose": T("Find over-privileged, long-lived or exposed machine credentials before they are abused.", "在被滥用前，找出权限过大、长期有效或已暴露的机器凭证。"),
     "system": "You are a non-human-identity governance assistant reviewing the organization's own inventory. Given service accounts, tokens and keys with their scopes and ages, rank the riskiest (non-expiring, over-scoped, public-facing, reused) and recommend a scoping/expiry fix for each. JSON only.",
     "task": "Identity inventory:\n<<NHI_JSON>>\nReturn ranked_risks[] with {identity, risk_reason, fix}."},
    {"id": "P12", "name": T("Leaked-secret exposure triage", "泄露密钥暴露研判"), "model": T("Embedding search + LLM", "嵌入检索 + LLM"),
     "purpose": T("Assess secrets found in public assets for validity and blast radius.", "评估公开资产中发现的密钥的有效性与爆炸半径。"),
     "system": "You are a secret-exposure triage assistant for the organization's own public assets. Given candidate secrets discovered in public data, classify each as likely_live|likely_stale|test, estimate blast radius, and set a rotation priority. Reference secrets by location/identifier, never echo full values. JSON only.",
     "task": "Findings:\n<<SECRET_FINDINGS_JSON>>\nReturn triaged[] with {location, status, blast_radius, priority}."},
    {"id": "P13", "name": T("Executive incident brief", "高管事件简报"), "model": T("Self-hosted LLM", "自托管LLM"),
     "purpose": T("Turn the technical findings into an answer-first brief for leadership.", "把技术发现转化为面向管理层、结论先行的简报。"),
     "system": "You are a security communications assistant. Given the incident findings, write an answer-first executive brief using SCQA: one-line bottom line, then situation, complication, what we did, residual risk and the decision you need. Plain language, no jargon, under 250 words.",
     "task": "Findings:\n<<FINDINGS_JSON>>\nReturn the brief."},
    {"id": "P14", "name": T("Adversary emulation (purple-team) planning", "对手仿真（紫队）规划"), "model": T("Self-hosted LLM", "自托管LLM"),
     "purpose": T("Design safe, authorized drills that test whether the defense would catch a similar agent swarm.", "设计安全、经授权的演练，检验防御能否发现类似的智能体集群。"),
     "system": "You are a purple-team planner for authorized, in-scope security drills on the organization's own test environment. Propose objective-level test scenarios (e.g. 'detect a session that shifts from normal use to machine-cadence probing', 'detect enrolment of a rogue overlay-network device') and the exact telemetry and detection each should exercise. Describe scenarios at the objective/behaviour level only — no exploit code or step-by-step intrusion instructions. JSON only.",
     "task": "Scope & assets:\n<<SCOPE_JSON>>\nReturn scenarios[] with {objective, telemetry_exercised, expected_detection, pass_criteria}."},
]
