# Numbered source list for the research dataset (access date 2026-09-25).
# Evidence note: primary pages could not be fetched from the research
# environment (egress proxy); claims are triangulated from search-result
# summaries of these sources.

SOURCES = [
    ("S1", "Security incident disclosure — July 2026", "Hugging Face", "2026-07-16", "https://huggingface.co/blog/security-incident-july-2026"),
    ("S2", "Anatomy of a Frontier Lab Agent Intrusion: A Technical Timeline of the July 2026 Incident", "Hugging Face", "2026-07-27", "https://huggingface.co/blog/agent-intrusion-technical-timeline"),
    ("S3", "The Hugging Face incident and the road ahead", "OpenAI", "2026-08-26", "https://openai.com/index/hugging-face-incident-and-the-road-ahead/"),
    ("S4", "Hugging Face Incident Technical Report (PDF)", "OpenAI", "2026-08-26", "https://cdn.openai.com/pdf/67869394-cb91-4c12-888c-5cbd85c7814c/OpenAI-Hugging-Face%20Incident-Technical-Report.pdf"),
    ("S5", "Brief independent investigation of agents' behavior, reasoning and collaboration in the OpenAI / Hugging Face hacking incident", "METR & Redwood Research", "2026-08-26", "https://metr.org/blog/2026-08-26-openai-hugging-face-incident-investigation/"),
    ("S6", "OpenAI–HuggingFace incident", "Wikipedia", "2026-09", "https://en.wikipedia.org/wiki/OpenAI%E2%80%93HuggingFace_incident"),
    ("S7", "How a Chinese AI model stopped OpenAI's 'unprecedented' cyber attack", "CNBC", "2026-07-24", "https://www.cnbc.com/2026/07/24/chinese-ai-model-openai-cyber-attack.html"),
    ("S8", "Hugging Face uses open-weights Z.ai GLM-5.2 to defend against attacker after commercial frontier model refusal", "SiliconANGLE", "2026-07-20", "https://siliconangle.com/2026/07/20/hugging-face-uses-open-weights-z-ai-glm-5-2-defend-attacker-commercial-frontier-model-refusal/"),
    ("S9", "Hugging Face turns to Chinese open-source AI to fend off autonomous AI cyber attack after American AI guardrails stymie defense", "Fortune", "2026-07-20", "https://fortune.com/2026/07/20/hugging-face-turns-to-chinese-open-source-ai-to-fend-off-autonomous-ai-cyber-attack-after-american-ai-guardrails-stymie-defense/"),
    ("S10", "Hugging Face uses GLM 5.2 to investigate AI agent-driven cyberattack", "SC Media", "2026-07", "https://www.scworld.com/news/hugging-face-uses-glm-5-2-to-investigate-ai-agent-driven-cyberattack"),
    ("S11", "The Models Said No: Inside the Hugging Face Post-Mortem", "SANS Institute", "2026-08", "https://www.sans.org/blog/models-said-no-inside-hugging-face-post-mortem"),
    ("S12", "Tailscale didn't stop the Hugging Face intrusion", "Tailscale", "2026-08", "https://tailscale.com/blog/hugging-face-intrusion"),
    ("S13", "An autonomous AI agent compromised Hugging Face — the response is the real story", "Vectra AI", "2026-08", "https://www.vectra.ai/blog/an-autonomous-ai-agent-compromised-hugging-face-the-response-is-the-real-story"),
    ("S14", "Dissecting the Hugging Face Agent Intrusion", "Delinea", "2026-08", "https://delinea.com/blog/dissecting-the-hugging-face-agent-intrusion"),
    ("S15", "The 14 leaked API keys that fueled OpenAI's Hugging Face attack", "Truffle Security", "2026-08", "https://trufflesecurity.com/blog/the-stolen-keys-openai-used-to-breach-hugging-face"),
    ("S16", "Hugging Face details OpenAI agent's 13-hour escalation", "Implicator.ai", "2026-07", "https://www.implicator.ai/hugging-face-openai-agent-cluster-admin-13-hours/"),
    ("S17", "tl;dr sec #339", "tl;dr sec", "2026-08", "https://tldrsec.com/p/tldr-sec-339"),
    ("S18", "Hugging Face Incident Initial Post Mortem (CISO community guidance)", "Cloud Security Alliance", "2026-07-28", "https://cloudsecurityalliance.org/artifacts/hugging-face-ciso-post-mortem"),
    ("S19", "Hugging Face uses GLM-5.2 to run breach forensic analysis", "Daily Tech News Show", "2026-07-20", "https://dailytechnewsshow.com/2026/07/20/hugging-face-uses-glm-5-2-to-run-breach-forensic-analysis-dth/"),
    ("S20", "Hugging Face hack: OpenAI rogue model (interview with CEO Clem Delangue)", "CBS News", "2026-07", "https://www.cbsnews.com/news/hugging-face-hack-openai-rogue-model/"),
    ("S21", "Thomas Wolf (Hugging Face co-founder) post on the incident", "X", "2026-07", "https://x.com/Thom_Wolf/status/2079675541280411927"),
    ("S22", "The Rise and Fall of Agent Civilizations", "Dwarkesh Patel", "2026-08-29", "https://www.dwarkesh.com/p/openai-huggingface"),
    ("S23", "Ajeya Cotra – Inside the OpenAI agent swarm that hacked Hugging Face (podcast)", "Dwarkesh Podcast", "2026-09-01", "https://www.dwarkesh.com/p/ajeya-cotra"),
    ("S24", "Investigating three incidents in our cybersecurity evaluations", "Anthropic", "2026-07-30", "https://www.anthropic.com/news/investigating-incidents-cybersecurity-evals"),
    ("S25", "Cybersecurity researchers aren't happy about the guardrails on Anthropic's Fable", "TechCrunch", "2026-06-10", "https://techcrunch.com/2026/06/10/cybersecurity-researchers-arent-happy-about-the-guardrails-on-anthropics-fable/"),
    ("S26", "defenders-dilemma: forensic-task refusal replication on HF incident artifacts (third-party)", "GitHub (rkstu)", "2026-08", "https://github.com/rkstu/defenders-dilemma"),
    ("S27", "Be Ready Before the Attack: A Practical Guide to Self-Hosting an Open Model for Cyber Defense", "Hugging Face", "2026-08", "https://huggingface.co/blog/jeffboudier/open-model-cyber-defense"),
    ("S28", "Z.ai ships GLM-5.3 without retraining the base model", "MarkTechPost", "2026-08-14", "https://www.marktechpost.com/2026/08/14/z-ai-ships-glm-5-3-without-retraining-the-base-model-better-at-complex-coding-and-long-horizon-tasks/"),
    ("S29", "Nvidia, Microsoft, Meta warn against 'premature restrictions' of open-weight models", "CNBC", "2026-07-24", "https://www.cnbc.com/2026/07/24/nvidia-microsoft-meta-open-weight-ai-models.html"),
    ("S30", "Hugging Face CEO calls for 'radical transparency' after unprecedented OpenAI hack", "TechCrunch", "2026-07-26", "https://techcrunch.com/2026/07/26/hugging-face-ceo-calls-for-radical-transparency-after-unprecedented-openai-hack/"),
    ("S31", "OpenAI agent exploited JFrog Artifactory flaw, abused Modal customer sandbox", "SC Media", "2026-08", "https://www.scworld.com/news/openai-agent-exploited-jfrog-artifactory-flaw-abused-modal-customer-sandbox"),
    ("S32", "OpenAI–Hugging Face incident: lateral movement analysis", "Elisity", "2026-08", "https://www.elisity.com/blog/openai-hugging-face-incident-lateral-movement"),
    ("S33", "OpenAI says Hugging Face breach caused by one of its models", "Axios", "2026-07-21", "https://www.axios.com/2026/07/21/openai-says-hugging-face-breach-caused-by-one-its-models"),
    ("S34", "Hugging Face confirms breach affected internal datasets and credentials, urges users to take action", "TechCrunch", "2026-07-20", "https://techcrunch.com/2026/07/20/hugging-face-confirms-breach-affected-internal-datasets-and-credentials-urges-users-to-take-action/"),
    ("S35", "Casar responds to OpenAI, Anthropic; demands greater transparency", "Office of Rep. Greg Casar", "2026-08", "https://casar.house.gov/media/press-releases/casar-responds-openai-anthropic-demands-greater-transparency-about-major"),
    ("S36", "OpenAI explains how its AI agents attacked Hugging Face", "The Register", "2026-08-27", "https://www.theregister.com/security/2026/08/27/openai-explains-how-its-naughty-ai-agents-attacked-hugging-face/5292780"),
    ("S37", "Three Reports, One Break-in: the Hugging Face incident from three sides", "DEV Community (A. Grebenkin)", "2026-08", "https://dev.to/avgrebenkin/three-reports-one-break-in-the-hugging-face-incident-from-three-sides-58p"),
    ("S38", "The OpenAI Hack Is Fueling a New Fight Over Open-Source AI", "TIME", "2026-07-28", "https://time.com/article/2026/07/28/open-source-ai-hugging-face-openai/"),
    ("S39", "OpenAI's rogue agents used more than 10 additional sites for unauthorized comms (Reuters)", "The Globe and Mail", "2026-09-16", "https://www.theglobeandmail.com/business/article-openai-rogue-agents-artificial-intelligence/"),
    ("S40", "Medicare Australia: 'Extreme concern' over OpenAI breach of health database", "CNN Business", "2026-09-23", "https://www.cnn.com/2026/09/23/business/australia-openai-agent-hack-intl-hnk"),
    ("S41", "OpenAI agents attack the 'first' government hack by autonomous AI, researchers say", "ABC News (Australia)", "2026-09-24", "https://www.abc.net.au/news/2026-09-24/openai-agents-plotted-to-access-data-amid-medicare-hack/107189504"),
    ("S42", "OpenAI says agent hacked Australian government website without being told to do so", "CNBC", "2026-09-24", "https://www.cnbc.com/2026/09/24/openai-agent-hacked-australian-government-website-.html"),
    ("S43", "Australian prime minister says OpenAI agent hacked healthcare website", "The Washington Post", "2026-09-23", "https://www.washingtonpost.com/technology/2026/09/23/australian-prime-minister-says-openai-agent-hacked-healthcare-website/"),
    ("S44", "How an OpenAI 'agent' hacked Australia's Medicare and what that means", "Al Jazeera", "2026-09-24", "https://www.aljazeera.com/news/2026/9/24/how-an-openai-agent-hacked-australias-medicare-and-what-that-means"),
    ("S45", "PM calls OpenAI hack of Medicare 'unacceptable'; three other government systems potentially compromised", "Cyber Daily", "2026-09-24", "https://www.cyberdaily.au/security/14223-breached-pm-calls-openai-hack-of-medicare-unacceptable-three-other-government-systems-potentially-compromised"),
    ("S46", "OpenAI's agents went after government and university sites months before Hugging Face", "The Decoder", "2026-09-24", "https://the-decoder.com/openais-agents-went-after-government-and-university-sites-months-before-hugging-face/"),
    ("S47", "Report reveals yet more cases of OpenAI's 'rogue AI' agents hacking websites, including a crypto exchange in September", "Fortune", "2026-09-24", "https://fortune.com/2026/09/24/openai-more-rogue-ai-agents-hacking-websites-cryptoexchange-in-september-research-report-transluce/"),
    ("S48", "OpenAI Agents Probed Websites for Vulnerabilities While Fetching Public Data", "SecurityWeek", "2026-09-24", "https://www.securityweek.com/openai-agents-probed-websites-for-vulnerabilities-while-fetching-public-data/"),
    ("S49", "Early rogue AI agent activity and attempts to hack found on urlquery.net", "Transluce", "2026-09", "https://transluce.org/agent-activity"),
    ("S50", "OpenAI agents breached Australian portal, attempted other hacks", "Axios", "2026-09-24", "https://www.axios.com/2026/09/24/openai-agents-australia-data-breach"),
    ("S51", "OpenAI's rogue AI agents used universities, wikis, and text-sharing sites as hidden message boards", "Fortune", "2026-09-09", "https://fortune.com/2026/09/09/openai-rogue-ai-agents-reached-12-more-websites/"),
    ("S52", "Rogue AI agents reportedly turned a University of Toronto tool into a message board", "CBC News", "2026-09", "https://www.cbc.ca/news/canada/openai-university-toronto-rogue-agents-link-shortener-ai-9.7349607"),
    ("S53", "OpenAI Agents Linked to RubyGems Campaign That Gained RCE on RubyDoc Servers", "The Hacker News", "2026-09", "https://thehackernews.com/2026/09/openai-agents-linked-to-rubygems.html"),
    ("S54", "Gemini hacked three companies in first known breakout by Google's AI", "CNN Business", "2026-09-19", "https://www.cnn.com/2026/09/19/business/gemini-ai-hack-internet"),
    ("S55", "An alignment assessment of recent cybersecurity incidents", "Anthropic", "2026-09-09", "https://www.anthropic.com/research/alignment-assessment-cybersecurity-incidents"),
    ("S56", "Countering misuse of AI: September 2026", "Anthropic", "2026-09-10", "https://www.anthropic.com/threat-intelligence-report-september-2026"),
    ("S57", "Disrupting an AI-orchestrated cyber espionage campaign (GTG-1002)", "Anthropic", "2025-11-13", "https://www.anthropic.com/news/disrupting-AI-espionage"),
    ("S58", "GTIG AI Threat Tracker: From Prompting to Autonomy", "Google Threat Intelligence Group", "2026", "https://cloud.google.com/blog/topics/threat-intelligence/from-prompting-to-autonomy-the-evolution-of-adversarial-ai"),
    ("S59", "Hundreds of AI agents helped PaperCut attacker hit 395 orgs, and some went off script", "The Register", "2026-09-10", "https://www.theregister.com/security/2026/09/10/hundreds-of-ai-agents-helped-papercut-attacker-hit-395-orgs-and-some-went-off-script/5295650"),
    ("S60", "AI agents exploited PaperCut flaws to breach 395 organizations", "Help Net Security", "2026-09-11", "https://www.helpnetsecurity.com/2026/09/11/ai-agents-papercut-ng-mf-attack-campaign/"),
    ("S61", "Hacker Runs Hermes AI Agent Unattended for Post-Exploitation at Thai Finance Ministry", "The Hacker News", "2026-07", "https://thehackernews.com/2026/07/hacker-runs-hermes-ai-agent-unattended.html"),
    ("S62", "Thailand's Ministry of Finance targeted with Hermes AI agent", "Hunt.io", "2026-07", "https://hunt.io/blog/thailand-ministry-finance-targeted-with-hermes-ai-agent"),
    ("S63", "Spain reports first data breach involving autonomous AI agent", "Help Net Security", "2026-09-17", "https://www.helpnetsecurity.com/2026/09/17/spain-ai-agent-data-breach/"),
    ("S64", "Careful Adoption of Agentic AI Services (joint guidance CISA / ASD-ACSC / NSA / CCCS / NCSC)", "CISA, ASD's ACSC et al.", "2026-04-30", "https://media.defense.gov/2026/Apr/30/2003922823/-1/-1/0/CAREFUL%20ADOPTION%20OF%20AGENTIC%20AI%20SERVICES_FINAL.PDF"),
    ("S65", "ACSC issues warning over AI misalignment risks (High Alert)", "Cyber Daily", "2026-09-24", "https://www.cyberdaily.au/security/14225-alert-australian-cyber-security-centre-issues-warning-over-ai-misalignment-risks"),
    ("S66", "OpenAI's shared-memory agents", "Turing Post", "2026-09", "https://turingpost.substack.com/p/openais-shared-memory-agents-googles"),
    ("S67", "AI Is Developing a Culture of Its Own. That Could Be Dangerous", "TIME", "2026-09-10", "https://time.com/article/2026/09/10/ai-openai-hugging-face-hack-culture-swarm/"),
    ("S68", "Teams of LLM Agents can Exploit Zero-Day Vulnerabilities (HPTSA)", "arXiv 2406.01637", "2024/2026", "https://arxiv.org/abs/2406.01637"),
    ("S69", "Data USA", "Wikipedia", "2026", "https://en.wikipedia.org/wiki/Data_USA"),
    ("S70", "Swarm of OpenAI Agents Exploit Artifactory Zero-Day to Escape Sandbox and Breach Hugging Face", "InfoQ", "2026-08", "https://www.infoq.com/news/2026/08/openai-huggingface-breach/"),
    ("S71", "2026 OpenAI agent cyberattacks", "Wikipedia", "2026-09", "https://en.wikipedia.org/wiki/2026_OpenAI_agent_cyberattacks"),
    ("S72", "AI lets small actors run state-level hacking campaigns, Anthropic report finds", "CyberScoop", "2026-09", "https://cyberscoop.com/anthropic-report-ai-enabled-cyber-attacks/"),
    ("S73", "Mandiant AI Risk and Resilience Report 2026", "Google Cloud / Mandiant", "2026", "https://cloud.google.com/security/resources/ai-risk-and-resilience-2026"),
    ("S74", "Financial Times article supplied by the user (headline not retrievable from the research environment)", "Financial Times", "2026-09", "https://www.ft.com/content/2a77e2f7-3c22-4082-8bb3-492675f46c77"),
    ("S75", "Researchers link more cyberattacks to OpenAI agent swarm", "SiliconANGLE", "2026-09-24", "https://siliconangle.com/2026/09/24/researchers-link-more-cyberattacks-to-openai-agent-swarm/"),
    ("S76", "Hugging Face AI agent intrusion: Qualys detection mapping", "Qualys", "2026-08-26", "https://blog.qualys.com/product-tech/2026/08/26/hugging-face-ai-agent-intrusion-qualys-detection-mapping"),
    ("S77", "Hugging Face breached by autonomous AI agent", "Help Net Security", "2026-07-20", "https://www.helpnetsecurity.com/2026/07/20/hugging-face-breached-by-autonomous-ai-agent/"),
]
