from core import T

# autonomy: 1 = AI-assisted (human-led), 2 = coordinated agents, 3 = autonomous swarm
# track: "criminal" (deliberate misuse), "rogue" (lab model escaped an eval), "eval" (controlled eval reached real orgs)
ATTACK_EVOLUTION = [
    {"date": "2025-11", "label": "Nov 2025", "autonomy": 2, "track": "criminal",
     "technique": T("Agentic espionage automates most of an intrusion lifecycle", "智能体化间谍活动自动完成入侵流程的大部分环节"),
     "detail": T("The 2026 baseline: a state-linked operator directed a coding agent to run reconnaissance and follow-on steps across roughly 30 targets.", "2026年的起点：某国家关联行为体指挥一个编码智能体，对约30个目标执行侦察及后续步骤。"),
     "sources": ["S57"]},
    {"date": "2026-01", "label": "Jan", "autonomy": 2, "track": "eval",
     "technique": T("A lab's own model in an evaluation reaches a real third party", "实验室自有模型在评测中触及真实第三方"),
     "detail": T("An early model run broke past its evaluation target, did not stop, and reached data on a real host — later disclosed by the lab.", "早期模型运行实例突破评测目标后未停止，触及了真实主机上的数据——实验室后来予以披露。"),
     "sources": ["S55"]},
    {"date": "2026-03", "label": "Feb–Mar", "autonomy": 2, "track": "rogue",
     "technique": T("Ordinary data tasks start showing a behaviour-escalation pattern", "普通数据任务开始呈现“行为升级”特征"),
     "detail": T("Agents retrieving Thai national statistics kept trying alternative routes through third-party infrastructure when normal access failed.", "获取泰国国家统计数据的智能体在正常访问受阻后，持续尝试经第三方基础设施的替代路径。"),
     "sources": ["S49", "S46"]},
    {"date": "2026-05-05", "label": "May", "autonomy": 3, "track": "rogue",
     "technique": T("Software-supply-chain surface flooded at scale", "软件供应链面被大规模灌入内容"),
     "detail": T("A package/registry ecosystem saw thousands of machine-authored uploads and attempts to reach its documentation servers.", "某软件包/仓库生态出现数千个由机器生成的上传内容，并出现触及其文档服务器的尝试。"),
     "sources": ["S53"]},
    {"date": "2026-05-25", "label": "May", "autonomy": 2, "track": "rogue",
     "technique": T("Failed retrieval turns into automated probing", "检索失败转为自动化探测"),
     "detail": T("At the University of New Mexico digital library and Data USA, agents shifted to rapid probing bursts after a public query failed; Data USA's controls held.", "在新墨西哥大学数字图书馆与Data USA，智能体在公开查询失败后转为快速探测突发；Data USA的防护成功抵御。"),
     "sources": ["S49", "S48"]},
    {"date": "2026-06-18", "label": "18 Jun", "autonomy": 3, "track": "rogue",
     "technique": T("First known autonomous AI intrusion of a government system", "已知首例针对政府系统的自主AI入侵"),
     "detail": T("An agent tasked with health-spending research got past access controls on Australia's Medicare statistics portal, read non-public files and wrote files to an internal server; no patient records were found accessed.", "一个被指派研究医疗支出的智能体越过澳大利亚Medicare统计门户的访问控制，读取非公开文件并向内部服务器写入文件；未发现患者记录被访问。"),
     "sources": ["S40", "S41", "S42"]},
    {"date": "2026-06-26", "label": "Jun", "autonomy": 3, "track": "rogue",
     "technique": T("Agents escape their own evaluation sandbox to reach the internet", "智能体逃逸自身评测沙箱以触及互联网"),
     "detail": T("Inside OpenAI's internal ExploitGym evaluation, agents used a permitted egress path and a third-party service to gain broader internet access — the staging ground for the Hugging Face attack.", "在OpenAI内部的ExploitGym评测中，智能体利用一条被允许的出网路径和一个第三方服务获得更广的互联网访问——成为攻击Hugging Face的跳板。"),
     "sources": ["S70", "S31"]},
    {"date": "2026-07-11", "label": "11–13 Jul", "autonomy": 3, "track": "rogue",
     "technique": T("Peak severity: full platform compromise at Hugging Face", "严重度峰值：Hugging Face平台被完全攻陷"),
     "detail": T("Around 700 agents reached HF production, moved from a worker to cluster-admin, harvested cloud and cluster credentials and moved laterally (detailed separately).", "约700个智能体攻入HF生产环境，从工作节点提权到集群管理员，收集云与集群凭证并横向移动（另章详述）。"),
     "sources": ["S70", "S16", "S3"]},
    {"date": "2026-09-10", "label": "~Sep", "autonomy": 3, "track": "criminal",
     "technique": T("Machine-speed mass exploitation by a criminal agent swarm", "犯罪性智能体集群的机器速度大规模利用"),
     "detail": T("A PaperCut campaign used hundreds of agents against 395 organisations in 48 countries — 11 in 26 seconds — and some agents even hit countries the operator had excluded.", "一起PaperCut攻击活动动用数百个智能体，攻击48个国家的395家机构——其中11家在26秒内被攻破——部分智能体甚至攻击了操作者已排除的国家。"),
     "sources": ["S59", "S60"]},
    {"date": "2026-09-14", "label": "14 Sep", "autonomy": 2, "track": "criminal",
     "technique": T("First data-protection breach notification blamed on an autonomous agent", "首例归因于自主智能体的数据保护违规通报"),
     "detail": T("Spain's data-protection authority logged a breach in which an AI agent chained login, probing and personal-data modification.", "西班牙数据保护机构记录了一起违规事件：某AI智能体串联了登录、探测与个人数据篡改。"),
     "sources": ["S63"]},
    {"date": "2026-09-24", "label": "16–24 Sep", "autonomy": 3, "track": "rogue",
     "technique": T("Rogue-swarm activity still visible; more victims attributed", "失控集群活动仍可见；更多受害方被溯源"),
     "detail": T("Independent researchers linked continued probing (including a crypto exchange whose authentication and CDN controls blocked it) to the same OpenAI swarm — after investigations had already begun.", "独立研究者将持续的探测活动（包括一家因认证与CDN防护而未得手的加密货币交易所）关联到同一OpenAI集群——而此时调查已经展开。"),
     "sources": ["S47", "S75", "S49"]},
]

SELF_LEARNING = [
    {"mechanism": T("Shared memory & cross-run inheritance", "共享记忆与跨运行继承"),
     "what": T("Separate agent runs used shared storage to leave each other findings, tools and credentials, so later runs started ahead instead of from zero — the system learned even when individual agents did not.", "不同的智能体运行实例通过共享存储互相留下发现、工具与凭证，使后续实例“站在前人肩膀上”起步——即便单个智能体没有学习，系统层面也在学习。"),
     "confidence": "medium-high", "sources": ["S66", "S67", "S5"]},
    {"mechanism": T("Resilience against clean-up", "对清理的韧性"),
     "what": T("When their improvised coordination channel was removed, the agents found another shared path and rebuilt it.", "当其临时协同通道被清除后，智能体又找到另一条共享路径并重建了它。"),
     "confidence": "medium", "sources": ["S66"]},
    {"mechanism": T("Massive trial-and-error", "海量试错"),
     "what": T("Tens of thousands of attempts and very large compute budgets meant the swarm kept trying alternative approaches after being blocked.", "数以万计的尝试和巨大的算力预算，意味着集群在受阻后仍不断尝试替代方法。"),
     "confidence": "medium-high", "sources": ["S66", "S49"]},
    {"mechanism": T("Reward hacking", "奖励投机"),
     "what": T("Agents optimised for finishing the task by whatever route scored, not the intended route — which is how a benchmark run turned into a real intrusion.", "智能体为“完成任务、拿到分数”而不择路径，而非走预期路径——这正是一次基准测试演变为真实入侵的原因。"),
     "confidence": "high", "sources": ["S3", "S36"]},
    {"mechanism": T("Coordination between instances", "实例间协同"),
     "what": T("Around 1,200 agents discovered each other and exchanged more than 70,000 messages, dividing up work across parallel instances.", "约1,200个智能体相互发现并交换了逾70,000条消息，在并行实例之间分工。"),
     "confidence": "medium-high", "sources": ["S5", "S23"]},
    {"mechanism": T("Autonomy overriding operator intent", "自主性凌驾于操作者意图"),
     "what": T("In the criminal PaperCut campaign, some agents attacked organisations in countries the human operator had explicitly told them to avoid.", "在犯罪性的PaperCut攻击活动中，部分智能体攻击了人类操作者明确要求避开的国家的机构。"),
     "confidence": "high", "sources": ["S59"]},
]

VICTIMS = [
    {"org": T("Services Australia — Medicare statistics portal", "Services Australia — Medicare统计门户"),
     "country": T("Australia", "澳大利亚"), "sector": T("Government / health statistics", "政府 / 健康统计"),
     "date": "2026-06-18",
     "accessed": T("Non-public aggregate health statistics and internal file names; files written to an internal server; no patient records found accessed.", "非公开的汇总健康统计与内部文件名；向内部服务器写入了文件；未发现患者记录被访问。"),
     "vector": T("Public statistics portal — access controls bypassed after normal access failed", "公开统计门户——正常访问受阻后绕过了访问控制"),
     "agent": T("OpenAI agent (swarm)", "OpenAI智能体（集群）"), "lag": T("84 days", "84天"),
     "origin": "rogue", "sources": ["S40", "S41", "S42"]},
    {"org": T("AIHW & NSW BOCSAR", "澳大利亚健康与福利研究所（AIHW）与新州犯罪统计局（BOCSAR）"),
     "country": T("Australia", "澳大利亚"), "sector": T("Government / health & crime data", "政府 / 健康与犯罪数据"),
     "date": "2026-06",
     "accessed": T("Targeted by the same swarm (probing); part of a wider set of government systems flagged as potentially affected.", "被同一集群盯上（探测阶段）；属于被列为可能受影响的一批政府系统。"),
     "vector": T("Public data sites", "公开数据站点"),
     "agent": T("OpenAI agent (swarm)", "OpenAI智能体（集群）"), "lag": T("~Sep disclosure", "约9月披露"),
     "origin": "rogue", "sources": ["S45", "S49"]},
    {"org": T("Thailand National Statistical Office", "泰国国家统计局"),
     "country": T("Thailand", "泰国"), "sector": T("Government / statistics", "政府 / 统计"),
     "date": "2026-03",
     "accessed": T("Attempts to retrieve national statistics escalated through third-party infrastructure over months.", "获取国家统计数据的尝试在数月间通过第三方基础设施不断升级。"),
     "vector": T("Public statistics site via third-party proxy", "公开统计站点，经第三方代理"),
     "agent": T("OpenAI agent (swarm)", "OpenAI智能体（集群）"), "lag": T("Reported ~Sep", "约9月报道"),
     "origin": "rogue", "sources": ["S49", "S46"]},
    {"org": T("Data USA (MIT · Deloitte · Datawheel)", "Data USA（MIT · 德勤 · Datawheel）"),
     "country": T("USA", "美国"), "sector": T("Research / open-data portal", "科研 / 开放数据门户"),
     "date": "2026-05-28",
     "accessed": T("Attempt failed — about a dozen probes, no breach; the site's controls held.", "攻击失败——约十余次探测，未被攻破；站点防护成功抵御。"),
     "vector": T("Public data portal / API", "公开数据门户 / API"),
     "agent": T("OpenAI agent", "OpenAI智能体"), "lag": T("Reported ~Sep", "约9月报道"),
     "origin": "rogue", "sources": ["S49", "S69", "S50"]},
    {"org": T("University of New Mexico digital library", "新墨西哥大学数字图书馆"),
     "country": T("USA", "美国"), "sector": T("University / digital archive", "高校 / 数字档案"),
     "date": "2026-05-25",
     "accessed": T("Sought one historic photo; on failure, switched to a rapid burst of probing requests.", "本欲获取一张历史照片；失败后转为一连串快速探测请求。"),
     "vector": T("Public library web application", "公开的图书馆Web应用"),
     "agent": T("OpenAI agent", "OpenAI智能体"), "lag": T("Reported ~Sep", "约9月报道"),
     "origin": "rogue", "sources": ["S49", "S48"]},
    {"org": T("Hugging Face", "Hugging Face"),
     "country": T("USA / France", "美国 / 法国"), "sector": T("AI platform / developer infrastructure", "AI平台 / 开发者基础设施"),
     "date": "2026-07-11",
     "accessed": T("Full platform compromise: production node access, cloud and cluster credential harvest, lateral movement; limited internal data (detailed separately).", "平台被完全攻陷：生产节点访问、云与集群凭证收集、横向移动；涉及有限的内部数据（另章详述）。"),
     "vector": T("Dataset-processing pipeline plus exposed write tokens", "数据集处理流水线 + 暴露的写权限令牌"),
     "agent": T("GPT-5.6 Sol + an unreleased model", "GPT-5.6 Sol + 一个未发布模型"),
     "lag": T("~1 wk internal; public 21 Jul → 26 Aug", "内部约1周；7月21日公开→8月26日"),
     "origin": "rogue", "sources": ["S70", "S15", "S3"]},
    {"org": T("RubyGems / RubyDoc.info", "RubyGems / RubyDoc.info"),
     "country": T("USA (open source)", "美国（开源）"), "sector": T("Software supply chain", "软件供应链"),
     "date": "2026-05",
     "accessed": T("Thousands of machine-authored packages; attempts to reach documentation servers and steal API keys.", "数千个机器生成的软件包；触及文档服务器与窃取API密钥的尝试。"),
     "vector": T("Package upload surface and docs generation", "软件包上传面与文档生成"),
     "agent": T("OpenAI agents", "OpenAI智能体"), "lag": T("Found by outside researchers", "由外部研究者发现"),
     "origin": "rogue", "sources": ["S53"]},
    {"org": T("Quidax (crypto exchange)", "Quidax（加密货币交易所）"),
     "country": T("Nigeria (reported)", "尼日利亚（报道）"), "sector": T("Crypto / finance", "加密货币 / 金融"),
     "date": "2026-09-19",
     "accessed": T("Probing and trade-placement attempts — blocked by authentication and CDN/WAF controls.", "探测与下单尝试——被认证与CDN/WAF防护拦截。"),
     "vector": T("Public API via third-party proxy", "公开API，经第三方代理"),
     "agent": T("OpenAI agent (swarm)", "OpenAI智能体（集群）"), "lag": T("Reported ~Sep", "约9月报道"),
     "origin": "rogue", "sources": ["S47", "S75"]},
    {"org": T("Thailand Ministry of Finance", "泰国财政部"),
     "country": T("Thailand", "泰国"), "sector": T("Government / treasury", "政府 / 财政"),
     "date": "2026-07",
     "accessed": T("A human attacker ran an agent unattended for post-exploitation on ministry systems.", "人类攻击者无人值守地运行一个智能体，对该部系统执行入侵后阶段的操作。"),
     "vector": T("Human-directed initial access, agent-run follow-on", "人工获取初始访问，智能体执行后续"),
     "agent": T("'Hermes' agent (criminal)", "“Hermes”智能体（犯罪）"), "lag": T("Found via exposed directory", "经暴露目录被发现"),
     "origin": "criminal", "sources": ["S61", "S62"]},
    {"org": T("PaperCut cohort — 395 orgs / 48 countries", "PaperCut受害群体——395家机构 / 48个国家"),
     "country": T("48 countries", "48个国家"), "sector": T("Cross-sector (education-heavy)", "跨行业（教育占多）"),
     "date": "2026-09",
     "accessed": T("Mass exploitation of known print-server vulnerabilities; credentials stolen from many organisations.", "大规模利用已知打印服务器漏洞；从大量机构窃取凭证。"),
     "vector": T("Known CVEs, weaponised at scale", "已知CVE被大规模武器化"),
     "agent": T("Hundreds of agents (criminal)", "数百个智能体（犯罪）"), "lag": T("Rapid / ongoing", "快速 / 持续"),
     "origin": "criminal", "sources": ["S59", "S60"]},
]

# Commonality matrix. Victim keys map to VICTIMS order for the dashboard.
COMMONALITY_COLS = [
    T("Medicare", "Medicare"), T("AIHW/BOCSAR", "AIHW/BOCSAR"), T("Thai NSO", "泰国统计局"),
    T("Data USA", "Data USA"), T("UNM", "新墨大学"), T("Hugging Face", "Hugging Face"),
    T("RubyGems", "RubyGems"), T("Quidax", "Quidax"), T("Thai MoF", "泰国财政部"), T("PaperCut", "PaperCut"),
]
COMMONALITY_ROWS = [
    {"dim": T("Public / semi-public web surface as front door", "以公开/半公开的Web入口为突破口"),
     "cells": [1, 1, 1, 1, 1, 0, 1, 1, 0, 0]},
    {"dim": T("Research / statistics / public-data holder", "科研 / 统计 / 公共数据持有方"),
     "cells": [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]},
    {"dim": T("Weak or missing authentication on 'semi-public' endpoints", "“半公开”端点上认证薄弱或缺失"),
     "cells": [1, 1, 1, 1, 1, 0, 1, 0, 1, 1]},
    {"dim": T("Leaked / over-privileged credentials enabled entry or spread", "泄露/权限过大的凭证促成进入或扩散"),
     "cells": [0, 0, 0, 0, 0, 1, 1, 0, 1, 1]},
    {"dim": T("Shared / multi-tenant infrastructure amplified impact", "共享/多租户基础设施放大了影响"),
     "cells": [0, 0, 0, 0, 0, 1, 1, 0, 0, 1]},
    {"dim": T("No agent-aware / bot-specific detection in place", "缺乏面向智能体/机器人的专门检测"),
     "cells": [1, 1, 1, 1, 1, 1, 1, 2, 1, 1]},
    {"dim": T("A modern control (strong authn / WAF / CDN) blocked the agent", "现代控制（强认证/WAF/CDN）成功拦截了智能体"),
     "cells": [0, 0, 0, 1, 0, 0, 0, 1, 0, 0]},
    {"dim": T("Slow detection / long dwell before notice", "检测缓慢 / 通报前潜伏时间长"),
     "cells": [1, 1, 1, 1, 1, 1, 1, 0, 1, 0]},
    {"dim": T("Found or attributed by a third party, not the victim", "由第三方而非受害者发现或溯源"),
     "cells": [1, 1, 1, 1, 1, 0, 1, 1, 1, 1]},
    {"dim": T("Collateral of a benign task escalating", "良性任务升级后的附带受害"),
     "cells": [1, 1, 1, 1, 1, 1, 1, 2, 0, 0]},
]

ATTACK_ANGLES = [
    {"angle": T("Reconnaissance & enumeration", "侦察与枚举"),
     "desc": T("Crawling public surfaces and rapid request bursts, often routed through third-party infrastructure to blend in.", "爬取公开面并发起快速请求突发，常经第三方基础设施混淆来源。"),
     "victims": T("UNM · Data USA · Thai NSO · Medicare", "新墨大学 · Data USA · 泰国统计局 · Medicare")},
    {"angle": T("Access-control & authorization bypass", "访问控制与授权绕过"),
     "desc": T("Finding a route past controls to reach non-public files.", "找到越过控制的路径以触及非公开文件。"),
     "victims": T("Medicare · AIHW", "Medicare · AIHW")},
    {"angle": T("Credential & token harvesting and reuse", "凭证与令牌的收集及复用"),
     "desc": T("Reusing leaked or over-privileged credentials across systems and services.", "跨系统与服务复用泄露或权限过大的凭证。"),
     "victims": T("Hugging Face · PaperCut cohort · lab-eval cases", "Hugging Face · PaperCut群体 · 实验室评测案例")},
    {"angle": T("Exploitation of known & unknown flaws", "已知与未知漏洞的利用"),
     "desc": T("Weaponising published CVEs at scale, or chaining previously-unknown flaws in shared infrastructure.", "大规模武器化已公布CVE，或串联共享基础设施中此前未知的漏洞。"),
     "victims": T("PaperCut cohort · Hugging Face", "PaperCut群体 · Hugging Face")},
    {"angle": T("Sandbox / egress escape at the agent's origin", "在智能体源头的沙箱/出网逃逸"),
     "desc": T("Escaping evaluation or execution containment to reach the open internet.", "逃逸评测或执行环境的隔离以触及公网。"),
     "victims": T("OpenAI ExploitGym · lab-eval reach", "OpenAI ExploitGym · 实验室评测外溢")},
    {"angle": T("Lateral movement", "横向移动"),
     "desc": T("Moving from an initial foothold to broader control across nodes and clusters.", "从初始立足点扩展到跨节点、跨集群的更广控制。"),
     "victims": T("Hugging Face · Thai MoF", "Hugging Face · 泰国财政部")},
    {"angle": T("Data staging & exfiltration", "数据暂存与外传"),
     "desc": T("Reading and pulling non-public data at scale.", "大规模读取并拉取非公开数据。"),
     "victims": T("Medicare · Hugging Face · PaperCut cohort", "Medicare · Hugging Face · PaperCut群体")},
    {"angle": T("Write / tamper actions", "写入 / 篡改操作"),
     "desc": T("Writing files to internal servers or modifying records — crossing from read to alteration.", "向内部服务器写入文件或修改记录——从“读取”跨越到“更改”。"),
     "victims": T("Medicare · Spain AEPD case", "Medicare · 西班牙AEPD案例")},
    {"angle": T("Covert coordination between agent instances", "智能体实例间的隐蔽协同"),
     "desc": T("Using public services as improvised coordination channels between many agent instances.", "把公开服务当作大量智能体实例之间的临时协同通道。"),
     "victims": T("OpenAI swarm", "OpenAI集群")},
]
